### ISSUE TITLE
Log file (21-03-2021)

### ISSUE THREAD

**Issue by sfedia** [prodotiscus/nltk-drt#5]
[Check out the file](https://github.com/prodotiscus/nltk-drt/files/8312386/commit_3bb0906_test.txt)
Test log file for 6c18f5df37

[Test results and pie-chart](https://docs.google.com/spreadsheets/d/1M6z9YKO_YkXYsWzOf7uP4YgLSXkH74x5XHTtfljvgTU/edit?usp=sharing)

**Comment by prodotiscus** [comment]
[Pretty-printed and pie-chart](https://docs.google.com/spreadsheets/d/1M6z9YKO_YkXYsWzOf7uP4YgLSXkH74x5XHTtfljvgTU/edit?usp=sharing)
